### ISSUE TITLE
Mirador 3 evaluation 

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#1]
Report on the state of Mirador 3 development to help determine its impact on the JHU’s infrastructure

**Comment by GroovinChip** [comment]
Here's my report as it stands now. I had assumed that I'd be presenting it, so it could probably be a bit more detailed. If you'd like me to flesh it our more, I will do so.

[Mirador 3 Report.docx](https://github.com/jhu-digital-manuscripts/AnIOp/files/3356653/Mirador.3.Report.docx)
