### ISSUE TITLE
Draft mockup(s) to address testing feedback

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/AnIOp#103]
The purpose is to propose a modified UI that we think addresses feedback that we've already received.

* Lack of interaction between annotation text in the sidebar makes it difficult to read the text and follow along in the manuscript image.
* It is difficult to read and follow along using only the translation
  * Possibly because of how the translation is split up and hidden in expansion panels?
  * Showing continuous translation could mean displaying page level translation, as opposed to sentence level
* Instead of showing individual maps for each georeference annotation, it would be helpful to collect all of them onto a single map for a given passage
  * Would it help to declutter the sidebar to move this map to a separate/new sidebar?
  * "for a given passage": how do we define a passage - page, paragraph, sentence, user selection, etc?

For now, we should be open to changes in the data model. It would be good to know if user feedback suggests such changes. 

We should also not necessarily limit ourselves to our current setup of a single sidebar that contains everything. Is it beneficial to break out pieces into different sidebars, for example? Mirador 3's recent update allows simpler creation of _new_ custom sidebars and adding them to windows, instead of replacing current ones.

**Comment by GroovinChip** [comment]
Ideas:
- Annotation highlighting
- Multiple sidebars for different things, like transcriptions, translations, map data
  - for a map data sidebar, maybe show a small preview will all map markers and then can expand the map into a modal window that shows the same map but larger. Also, map markers, when clicked, could show more of the detail that we currently show by default like tags

I will make some mockups and post them here.

**Comment by GroovinChip** [comment]
Below is a mockup of a "map data" sidebar that shows one map with all data points, and it has a button to expand the map into a modal window that shows the same map at a larger and more interactive size
![image](https://user-images.githubusercontent.com/4250470/85149224-083a7300-b21f-11ea-9d13-a3dd9445849d.png)

**Comment by GroovinChip** [comment]
![image](https://user-images.githubusercontent.com/4250470/85149720-9f072f80-b21f-11ea-9559-195c2caa413b.jpeg)

**Comment by GroovinChip** [comment]
@jabrah do you think I need to make mockups for what transcription-only/translation-only sidebars would look like? Seems pretty self evident, doesn't it?

**Comment by jabrah** [comment]
I think it would be helpful to have mockups for them, since they may be shown to Chiara and the other testers. If possible, notes about possible interaction between different elements would help as well to illustrate how we're thinking about this stuff

**Comment by GroovinChip** [comment]
> I think it would be helpful to have mockups for them, since they may be shown to Chiara and the other testers.

Fair enough

> If possible, notes about possible interaction between different elements would help as well to illustrate how we're thinking about this stuff

In the map data mockup I wrote a note about interaction, is that not enough for that one?

**Comment by jabrah** [comment]
Yeah the notes on the map mockup I think are good. I guess I just wanted to make sure that interaction notes would be present for transcription/translation stuffs

**Comment by GroovinChip** [comment]
![image](https://user-images.githubusercontent.com/4250470/85292760-68712500-b46a-11ea-99cb-a4ccfe3035be.png)
