### ISSUE TITLE
Annotation companion window needs a new button

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/AnIOp#106]
The annotation sidebar was recently updated to take advantage of Mirador 3's new CustomPanel plugin API. It requires that a custom button be defined that is added to the window's sidebar tab buttons to toggle the custom panel on. We currently have a placeholder button that is functional, but needs a new icon and needs to be changed to get the tooltip working correctly

**Comment by GroovinChip** [comment]
New button has been added. See branch custom-sidebar-button
