### ISSUE TITLE
Test mirador 3 support for IIIF 3

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/AnIOp#14]
This will have to wait until rosademo supports IIIF 3.

**Comment by markpatton** [comment]
Should check to see if Mirador 3 can do content negotiation for the IIIF version

**Comment by GroovinChip** [comment]
What do you mean by content negotiation

**Comment by markpatton** [comment]
> What do you mean by content negotiation

HTTP Content negotiation: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation
It needs both server and client support to be effective.

**Comment by htpvu** [comment]
Decision: we will be using IIIF2. close this task
