### ISSUE TITLE
Modify mirador 3 to use the rosademo web annotation service

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/AnIOp#15]
This is an experiment. 

For the moment the web annotation service could be hard coded, but also think about how best to represent this service in IIIF. Also think about how using IIIF 3 would change this.

**Comment by GroovinChip** [comment]
## Complete by 8/26/2019

- [x] Call WA service in Mirador 3 and put out a rough visual representation of the data.

   `https://rosetest.library.jhu.edu/rosademo/wa/rose/SeldenSupra57/1r/canvas`

- [x] Push code to github

- [x] Prepopulate manifests

- [x] Address #12 , talk to Derek or Jeff and get permission to deploy to server. get URL to be able to share with others on AnIop team.
- [x] Report results and determine next steps.
- [x] Dynamically show HTML rendered transcription for each canvas
- [x] Dynamically update endpoint UI based on view (part of previous)

**Comment by GroovinChip** [comment]
Updated task 4 to reflect current approach

**Comment by GroovinChip** [comment]
Task 5 is in progress. The button has been added, the challenge now is opening a panel.

**Comment by GroovinChip** [comment]
Updated tasks to reflect final approach

**Comment by GroovinChip** [comment]
Complete
