### ISSUE TITLE
Scaife server text as Web Annotation 

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#2]
Represent Scaife server text as a Web Annotation for evaluation.

**Comment by jtauber** [comment]
To clarify, we're not producing Web Annotation but rather consuming it. Basically taking a TEI text + standoff annotation in W3C Web Annotation format and, in ATLAS, producing a single JSON output with inline annotation for consumption by the Scaife Viewer.

**Comment by cyork** [comment]
I modified the comment to align with clarification. Let me know if it does not. 
Thanks.

**Comment by jacobwegner** [comment]
I think this can be best tracked via implementation of #5 and #10
