### ISSUE TITLE
Convert Homer translation alignment to W3C annotation format.

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#20]
Eldarion will convert homer translation alignment to W3C annotation

**Comment by jacobwegner** [comment]
We have a WA with the bounding box, greek, and english as part of https://github.com/scaife-viewer/hmt-cite-atlas/pull/2.  Given that the `targets` of those annotations include the CTS URN of the greek passage, they could serve the purposes of this ticket as well.
