### ISSUE TITLE
Ingest Homer Multitext into ATLAS

### ISSUE THREAD

**Issue by jtauber** [jhu-digital-manuscripts/AnIOp#23]

**Comment by jacobwegner** [comment]
Will expose text data for JHU's consumption

**Comment by jacobwegner** [comment]
The WAs implemented via https://github.com/scaife-viewer/hmt-cite-atlas/pull/2 are the start of this; we'll likely extract some annotations from the HMT data back over to http://github.com/scaife-viewer/explorehomer-atlas.

**Comment by jacobwegner** [comment]
As we continue some work within `explorehomer-atlas` to manage annotations and alignments, I've extracted HMT data in a new branch:

https://github.com/scaife-viewer/explorehomer-atlas/compare/master...spike/venetus-a?expand=1

will circle back to ingest the data to support #36, #7 and #9
