### ISSUE TITLE
Add endpoint for bulk export of Web Annotations

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/AnIOp#25]

**Comment by markpatton** [comment]
Done through AnnotationCollection. See the documentation here: https://github.com/jhu-digital-manuscripts/rosademo

**Comment by jacobwegner** [comment]
@markpatton I was able to use this for #10.  Thanks for your efforts!

I did have one small question we can discuss here or on the call later today.

Within a particular WA endpoint response:

e.g [https://rosetest.library.jhu.edu/rosademo/wa/rose/SeldenSupra57/1r/canvas/annotation](https://rosetest.library.jhu.edu/rosademo/wa/rose/SeldenSupra57/1r/canvas/annotation)
<img width="892" alt="image" src="https://user-images.githubusercontent.com/629062/67226813-795d2880-f3fb-11e9-862d-7fbe0703969e.png">

`target.source` is:
```JSON
{
  "type": "Canvas",
   "id": "http://rosetest.library.jhu.edu/rosademo/iiif/rose/SeldenSupra57/1r/canvas/annotation"
}
```

I get a 500 browsing to that URL
[https://rosetest.library.jhu.edu/rosademo/iiif/rose/SeldenSupra57/1r/canvas/annotation](https://rosetest.library.jhu.edu/rosademo/iiif/rose/SeldenSupra57/1r/canvas/annotation)

I _think_ it `target.source` should actually reference just `/canvas`:

```json
{
  "type": "Canvas",
   "id": "http://rosetest.library.jhu.edu/rosademo/iiif/rose/SeldenSupra57/1r/canvas"
}
```

[https://rosetest.library.jhu.edu/rosademo/iiif/rose/SeldenSupra57/1r/canvas](https://rosetest.library.jhu.edu/rosademo/iiif/rose/SeldenSupra57/1r/canvas)

This isn't a blocker to us, as I was able to "traverse" up the URL path to `/canvas`, but I wanted to double check my assumption with you in case there was something else intended with `/canvas/annotation` in this response.

**Comment by jacobwegner** [comment]
@markpatton and a second issue we had hit that isn't a blocker (we've coded around it), but worth mentioning:

The last page doesn't return valid JSON:

```
curl 'https://rosetest.library.jhu.edu/rosademo/wa/rose/SeldenSupra57/manifest/annotationpage/33' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   386  100   386    0     0   2404      0 --:--:-- --:--:-- --:--:--  2412
parse error: Unfinished JSON term at EOF at line 1, column 386
```

I think the last page should also be identified as https://rosetest.library.jhu.edu/rosademo/wa/rose/SeldenSupra57/manifest/annotationpage/32, since there are 324 items, and the first page starts at 0 (https://rosetest.library.jhu.edu/rosademo/wa/rose/SeldenSupra57/manifest/annotationpage/0)

**Comment by markpatton** [comment]
Looks like a few bugs. I should be able to add some tests and fix them up. Also the label property should be a string, not an object.

**Comment by markpatton** [comment]
Fixed label and incorrect IIIF resource in Web Annotation. 

Still need to fix incorrect json and Web Annotation objects using http instead of https.

**Comment by markpatton** [comment]
Ok. Fixed incorrect json for issue. Added missing next and prev attributes to annotation page. Only put last in annotation collection when needed. Also fixed https issue.
