### ISSUE TITLE
Mirador deployment on rosetest should show rose ms with transcriptions and homer ms by default

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/AnIOp#28]

**Comment by GroovinChip** [comment]
- Rose MS with Transcriptions: Is this one of the images from the endpoint that I'm already calling?
- Homer MS: I don't know what this is

**Comment by markpatton** [comment]
The homer ms is available as /homer/VA/manifest.

**Comment by GroovinChip** [comment]
All transcription manifests are now preloaded into Mirador.
