### ISSUE TITLE
Add web annotation to ATLAS returning simplified HTML content

### ISSUE THREAD

**Issue by jacobwegner** [jhu-digital-manuscripts/AnIOp#31]

**Comment by jacobwegner** [comment]
@markpatton and @GroovinChip:  I've stood up an endpoint to sample the type of simplified HTML we might return in a web annotation:

https://delarose-atlas.herokuapp.com/html/urn:cts:medievalmss:rose.SeldenSupra57:001r/

Given this isn't directly something being used by our front end, I'm looking for feedback on what might be useful to you as far as HTML in the web annotation.

The current HTML nests columns, line groups and lines, and notes if a line group is a couplet or stand alone line group:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/629062/67703042-c6ec0f00-f980-11e9-865a-65cb181e1ef5.png">

**Comment by markpatton** [comment]
@jacobwegner 

That approach looks good. There is enough information that we could easily do a little css styling.

**Comment by jacobwegner** [comment]
@markpatton I've updated our ATLAS deployment expose this HTML via web annotations:

- A collection, https://delarose-atlas.herokuapp.com/wa/urn:cts:medievalmss:rose.SeldenSupra57/html/annotation-collection/
- A page, https://delarose-atlas.herokuapp.com/wa/urn:cts:medievalmss:rose.SeldenSupra57/html/annotation-page/1/
- A single annotation, https://delarose-atlas.herokuapp.com/wa/urn:cts:medievalmss:rose.SeldenSupra57:006r/html/
