### ISSUE TITLE
Support web annotations in Mirador 3

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#33]
Note: this activity is additional to the approved proposal.

- [x] Work with Jack R. to incorporate this functionality in the code base.

- [x] Provide updates as progress is made

**Comment by GroovinChip** [comment]
Also tracked in #30

**Comment by GroovinChip** [comment]
Update note: Jack Reed has successfully updated the Mirador 3 sidebar to support Web Annotations in a basic manner. This code is currently undergoing tests and review on the Mirador side. I do not have an ETA for when it will land in their master branch.

**Comment by GroovinChip** [comment]
Jack has opened a pull request for this code: ProjectMirador/mirador#2898

**Comment by GroovinChip** [comment]
see #34
