### ISSUE TITLE
understand options to replace or modify the sidebar

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#42]
As an outcome of this ticket, please write up a document laying out the pros and cons in using two of the  integration approach (between Web Annotation and Mirador 3 interface): 
approach 1: popup from a button 
- pros:
- cons:

approach 2: side bar take over
- pros:
- cons: 

Please provide the link to the document in this ticket when you're done.

**Comment by cyork** [comment]
Expect to be updated on 2/21/2020

**Comment by GroovinChip** [comment]
The status of this ticket is that we are waiting for a pull request to Mirador (https://github.com/ProjectMirador/mirador/pull/2942) to be merged. This PR addresses a blocking bug that prevents further investigation into using the sidebar.

It does seem that we will be able to use the sidebar to accomplish our goals in a more fleshed out  way than we thought.

**Comment by htpvu** [comment]
@GroovinChip that's a great development. 

While waiting for response from Mirador, couldyou document what you know about the Pop up approach for the record, as described in the ticket description?

**Comment by htpvu** [comment]
@GroovinChip Please document your findings and observation for this ticket here https://docs.google.com/document/d/1CmGSARROMQ_YTplQkm_BJS2Oq5jtvjZ5mwoPRnFixD0/edit

**Comment by GroovinChip** [comment]
@htpvu document filled in

**Comment by GroovinChip** [comment]
Update: the pull request has been merged. I will be meeting with Jack at 2 PM today.

**Comment by GroovinChip** [comment]
Via https://github.com/GroovinChip/RoseDemo-FrontEnd/pull/1 we can now display Web Annotations in the Mirador 3 sidebar
