### ISSUE TITLE
ATLAS: Translation data

### ISSUE THREAD

**Issue by jacobwegner** [jhu-digital-manuscripts/AnIOp#45]

**Comment by jacobwegner** [comment]
@markpatton following on from [my comment on #46](https://github.com/jhu-digital-manuscripts/AnIOp/issues/46), what kind of data "shape" would be useful?

We can work to have an English translation (like https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-eng4:1.1-1.160/) ingested into ATLAS, but only the alignment data in #46 would currently be linked to folios and canvas/fragment identifiers.


Would it be useful to have a separate WA that is again keyed off of a folio identifier and contains:

- Canvas / fragment information
- Text or HTML of the English content

Or we could include a WA with only the translation text that is roughly aligned to the folio.

All of this seems to be a subset of the sentence level data we're already going to provide in #46 and I'm not sure if that would be useful or not.

**Comment by markpatton** [comment]
@jacobwegner 

I agree that this seems redundant given the sentence level WA. I suggest we work off the sentence level WA first and see if anything else is needed.

**Comment by jacobwegner** [comment]
Resolved by [explorehomer-atlas/pull/26](https://github.com/scaife-viewer/explorehomer-atlas/pull/26)

As documented in [AniOp ATLAS Documentation](https://docs.google.com/document/d/1XB0vYGxY1M420lmpJhLe2M3IfzcOQwBYFiwKGaDQ9ug/edit), the Passage Text Parts endpoint can be used to retrieve passages from the English translations.
