### ISSUE TITLE
ATLAS: Morphological data

### ISSUE THREAD

**Issue by jacobwegner** [jhu-digital-manuscripts/AnIOp#50]

**Comment by htpvu** [comment]
hi @jacobwegner I know we have discussed what work this ticket represents in the last meeting, but would you please add those details to the ticket at the time of closure for the record?

**Comment by jacobwegner** [comment]
@htpvu: Per discussions with @jtauber, this is a duplicate of #49, as we'll end up ingesting morphological data at the token level.
