### ISSUE TITLE
ATLAS: Named entity data

### ISSUE THREAD

**Issue by jacobwegner** [jhu-digital-manuscripts/AnIOp#54]

**Comment by jacobwegner** [comment]
We've ingested person named entities for the first twenty lines of the Iliad.

I've documented some of the relevant GraphQL queries and proposed how we might construct a web annotation here:

[Building a Web Annotation for Named Entity Data in ATLAS](https://docs.google.com/document/d/1A9MKZxv1d1xwd6aZFeg2ZjKHDIShN5ZzPUi_PJAzlP0/edit?usp=sharing)

**Comment by htpvu** [comment]
@markpatton @jabrah @GroovinChip please review.

**Comment by markpatton** [comment]
John and I left comments on the google doc.

**Comment by jacobwegner** [comment]
@markpatton and @jabrah: I've got the first iteration of the named entity annotation deployed and documented in [AniOp ATLAS Documentation](https://docs.google.com/document/d/1XB0vYGxY1M420lmpJhLe2M3IfzcOQwBYFiwKGaDQ9ug/edit?usp=sharing
).

I tried to follow the structure of the Georefernce annotation (https://rosetest.library.jhu.edu/rosademo/wa/homer/VA/VA035RN-0036/canvas), but like the translation alignment annotation, the data is served in an annotation collection driven by the folio URN:

An individual named entity;
https://explorehomer-feature-na-4qbljt.herokuapp.com/wa/urn:cite2:hmt:msA.v1:12r/named-entities/0/compound/

The first page in the collection:
https://explorehomer-feature-na-4qbljt.herokuapp.com/wa/urn:cite2:hmt:msA.v1:12r/named-entities/collection/compound/0/

The collection:
https://explorehomer-feature-na-4qbljt.herokuapp.com/wa/urn:cite2:hmt:msA.v1:12r/named-entities/collection/compound/

**Comment by markpatton** [comment]
@jacobwegner  

Looking through them these make sense to me and look correct.

**Comment by jacobwegner** [comment]
Resolved by [explorehomer-atlas/pull/31](https://github.com/scaife-viewer/explorehomer-atlas/pull/31)

The Named Entities web annotation has been documented within [AniOp ATLAS Documentation](https://docs.google.com/document/d/1XB0vYGxY1M420lmpJhLe2M3IfzcOQwBYFiwKGaDQ9ug/edit).
