### ISSUE TITLE
Provide feedback for the first round of georeference data representation and end point

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#67]
Please review the proposed web annotation representation of Georeference data as described here https://docs.google.com/document/d/1BeyLcSTBnSCZnkYjeqHu-oTKuDfdSKvZGmBWdZ6YmLE/edit#.

Please note the section titled "Proposed use of Web Annotation" for some specific areas items/questions that should be considered when reviewing the proposal and giving feedback. 

Please comment directly on the doc to start. We'll follow up with comments, slack messages and/or meetings request as appropriate. 

Thanks!

**Comment by jacobwegner** [comment]
I've just left some feedback from the Eldarion team.  Just to summarize:

- We think that focusing this annotation on places and leaving #54 for persons may result in a more straightforward implementation for a client.
- Mapping _TextPositionSelector_ values to the English translation (https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-eng4:2.480-2.840/) would make the annotation more useful
- With that mapping, it would be easier to resolve the annotation to a particular folio

**Comment by jacobwegner** [comment]
(and we're happy to discuss any possible mapping approaches further on a call or in Slack)

**Comment by markpatton** [comment]
Useful feedback. I've updated the google doc with some followup.
