### ISSUE TITLE
Iterate on Georeference service

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#68]
re: Design and implement service that gives web annotation of the underlying data.

**Comment by markpatton** [comment]
At the moment things to fix look like:
- Incorrect construction of CTS URNs to English translation
- Use CTS URNs to exact targeted phrase.
- Consider pleiadies URI to service instead of website. Think about how to indicate it is a service.

**Comment by markpatton** [comment]
Close to having this done. I need some feedback from @jabrah about the Pleiades URI.

**Comment by markpatton** [comment]
Deployed update which fixes the CTS URNs.
