### ISSUE TITLE
Create mockups of how Homer multi-text data may be used/displayed and interacted with on Mirador viewer

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#69]

**Comment by cyork** [comment]
Create screenshots to show this

**Comment by GroovinChip** [comment]
Using the plain text transcription from https://explorehomer-atlas-dev3.herokuapp.com/wa/urn:cite2:hmt:msA.v1:12r/translation-alignment/0/text/ I have made the following mockup of how I expect it to load in the sidebar:

![homer sidebar mockup](https://user-images.githubusercontent.com/4250470/75686995-1ada6d80-5c6b-11ea-9198-6371c5341869.png)

This follows the standard way that text annotations appear in the Mirador sidebar.

**Comment by htpvu** [comment]
(ticket) Metadata associated with each WA: are there ways to display some part of the metadata on the sidebar along with WA? Specifically annotation types, so the user knows what he/she is looking at?

Screenshots of the hotspot linking between sidebar and canvas.

**Comment by GroovinChip** [comment]
@htpvu please let me know if you need more screenshots

Annotation hover:
![firefox_Lf0Dlv5Whu](https://user-images.githubusercontent.com/4250470/75917747-7c940680-5e28-11ea-8eff-404134efb8d7.jpg)
Annotation select:
![firefox_Pqh8Z8ZgEq](https://user-images.githubusercontent.com/4250470/75917755-8158ba80-5e28-11ea-830e-e6028f75194f.jpg)

**Comment by htpvu** [comment]
@GroovinChip, is the image displayed of Homer Multi-text? Are the information on the side bar part of this annotation data? I really can't tell. 

If they are not, then what would be really helpful is the mockups from these screenshots, but the the type of content and webannotations we will be dealing with. Could you review and update the ticket accordingly?

Ideally, i'd like a mock up detailed enough to show to Chiara to get her reaction on whether such a UI would be of useful. But we can start with just mockups of the correct content.

**Comment by GroovinChip** [comment]
The images displayed in these screenshots are from the Mirador demo page, as you had requested at the meeting last week. They are not from our own project.

What is the level of priority between this, #70 and #72? Right now #70 is what I'm focusing on the most because once I can successfully show a popup when annotations are clicked, everything else becomes much easier to do.

**Comment by jabrah** [comment]
I'm just playing around with some ideas and will continue to add to this document periodically. I'm basically taking the approach of something that may look acceptable, but may not necessarily be technically feasible in Mirador. For example I still want to imagine what georef data may look like in Mirador.

https://docs.google.com/document/d/1R0yoNueWqhhxtsvfPKQwT2fr2jdp8QYXaR1utqg7AdI/edit?usp=sharing

**Comment by GroovinChip** [comment]
> 
> 
> I'm just playing around with some ideas and will continue to add to this document periodically. I'm basically taking the approach of something that may look acceptable, but may not necessarily be technically feasible in Mirador. For example I still want to imagine what georef data may look like in Mirador.
> 
> https://docs.google.com/document/d/1R0yoNueWqhhxtsvfPKQwT2fr2jdp8QYXaR1utqg7AdI/edit?usp=sharing

I've read this now @htpvu. No particular comments at the moment.
