### ISSUE TITLE
Investigate how to display different type of data in the sidebar

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#70]

**Comment by GroovinChip** [comment]
Jack says it is possible to implement annotations filtering in the sidebar - see https://github.com/ProjectMirador/mirador/issues/2946. We need to comment our use case and how we would like to filter annotations. @markpatton Could you please give me some more specific info about this so I can get involved with that issue? Useful info would be specific categories of annotations, and specifically how we think a researcher would need to use the filtering.

**Comment by GroovinChip** [comment]
Jack is not sure whether we can configure the default width if the sidebar. Requires further research.

**Comment by htpvu** [comment]
@GroovinChip Let's talk about this. It's not clear to me how getting involved in this mirador issue contribute to our goal for this ticket in particular and this project as a whole. maybe i'm missing something.

**Comment by GroovinChip** [comment]
Sure, I can clarify that for you

**Comment by GroovinChip** [comment]
Types of data that can be displayed (per https://github.com/jhu-digital-manuscripts/AnIOp/projects/1):

- Translation data
- Metrical data
- Named entity data
- Georeference data
- Audio data
- IIIF data
- Sentence-level translation data
- Word-level translation data

Currently, Web Annotation data can only be displayed as text in the annotation sidebar, per the out-of-the-box features of Mirador. We can, however, intercept click and hover events for those annotations. If there is no significant movement on the Mirador side to support more kinds of data and filtering that data, we might consider using the click events to show a popup window for any data besides for text.

**Comment by GroovinChip** [comment]
Per https://github.com/ProjectMirador/mirador/issues/2947 it appears we can customize the default width of the sidebar panel (this was a question Mark had, I believe). However, this requires modifying the Mirador source code and submitting a PR to them. I presume that this would be considered outside the scope of our work.

**Comment by htpvu** [comment]
We can not display different data besides text on the sidebar.

We will need to investigate if annotation can be clicked on to popup a larger and more customizable viewing areas for other WA types. 

We will need to investigate how to style the text annotation can be styled and format. 

(2 weeks)
