### ISSUE TITLE
Georeference web annotation has incorrect IIIF canvas ID

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/AnIOp#75]
The SpecificResource that is supposed to be pointing to a bad canvas ID. It looks very close to the actual URL that it should be using, except with an index number appended. `"https://rosetest.library.jhu.edu/rosademo/iiif/homer/VA/VA034VN-0536/canvas/1`

Sample from the georef service:

``` javascript
{
  "type": "SpecificResource",
  "partOf": [
    {
      "id": "https://rosetest.library.jhu.edu/rosademo/iiif/homer/VA/1/manifest",
      "type": "Manifest"
    }
  ],
  "source": {
    "type": "Canvas",
    "id": "https://rosetest.library.jhu.edu/rosademo/iiif/homer/VA/VA034VN-0536/canvas/1"
  }
}
```

**Comment by markpatton** [comment]
Good catch. Will fix.

**Comment by markpatton** [comment]
Fix deployed.
