### ISSUE TITLE
Create an annotation discovery service?

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/AnIOp#78]
Our IIIF resources currently don't have any direct references to the various web annotation endpoints that we want to associate. The custom Mirador plugin currently has to rely on some "magic strings" to be able to create URLs to these services. This doesn't seem like a good linked-data way of handling these associations.

I think a fairly nice way would be to point the IIIF resources to an external service that knows about these other annotation sources.

This is not strictly necessary for the demo. This ticket is mostly to track this as a potential enhancement.

**Comment by jacobwegner** [comment]
@jabrah: we had some prior discussion about this last fall:

https://github.com/jhu-digital-manuscripts/AnIOp/issues/37

**Comment by jabrah** [comment]
Ah, thanks for pointing me there
