### ISSUE TITLE
Create new React component to display an annotation: Annotation component

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#84]
[Required] Component will render text content
[Required] Link to web page that “identifies” the annotation. Link should open new browser tab (instead of opening in place)
[Required] Display sentence level translations from Eldarion

assigning this to JAbrahams, but may be directed to another developer

context:
https://docs.google.com/document/d/1FkWoD0NxULTJpaWBbBjgA8KeyPstvgL-qMduOm5hBeo/edit#

**Comment by jabrah** [comment]
At this point, all the  above required data is technically able to be displayed. I still need to do some work in order to dynamically resolve the sentence level translation annotations from Eldarion's endpoint. Will try generating CTS URNs from the canvas name first.
