### ISSUE TITLE
Decorate the Annotation to show annotations that target it

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#86]
**_This will be the difficult bit!_**

- How about having the React model include the annotation (the subject) and all annotations that target it? This way if another annotation is loaded that targets the subject annotation, this model will also be updated and React will re-render to update the DOM.

- Will likely have to be able to directly modify React component HTML if we want to use the TextQuoteSelector

assigning to JAbrahams for now, but may be re-assigned to another developer

 https://docs.google.com/document/d/1FkWoD0NxULTJpaWBbBjgA8KeyPstvgL-qMduOm5hBeo/edit#

**Comment by jabrah** [comment]
Now that a map is created by a custom selector, it's pretty straightforward to display targeted annotations. https://github.com/jhu-digital-manuscripts/rosademo-frontend/blob/display-eldarion-annos/src/plugins/jh-annotations-panel/components/annotation.js#L79-L93


![image](https://user-images.githubusercontent.com/5167587/79998736-12432e00-8489-11ea-99dc-3172c1428acb.png)
