### ISSUE TITLE
Think about layout/design of the annotations in our custom Mirador side panel

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/AnIOp#88]
Consider the different type of Web Annotations (namely, georeference, translation/transcription and named entity), please come up with proposal on how these WAs should be displayed to optimize the user experience. 

Some ideas

_in progress_

* Show only transcription/translation annotations in the sidebar, other annotations (that target the transcription/translation) can be hidden initially?
* Annotations that target transcriptions/translations can be rendered in a collapsible panel that is hidden on initial render

**Comment by GroovinChip** [comment]
https://github.com/jhu-digital-manuscripts/rosademo-frontend/pull/12 puts translation and georeference annotations inside expansion panels that are collapsed by default. Screenshot:
![chrome_h6S73Exia9](https://user-images.githubusercontent.com/4250470/81425736-28f2b180-9126-11ea-898c-394ef4e384d9.png)
