### ISSUE TITLE
Identify where to find information to drive map

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#93]
The WA will have Longitude and Latitude coordinate that will help drop a pinpoint on a map to be displayed.

**From previously shared information to Reuben from John:**
We could add a "map" component, or otherwise make use of the Pleiades data in a way that isn't just a simple clickable link.

**Comment by jabrah** [comment]
A bit more detail: The georef annotation has one body that has a purpose of _identifying_ which has a URL to a page in Pleiades. If we were to issue a request at the URL provided, using content negotiation, we should be able to retrieve the JSON data with the long/lat coordinates.

In this request, including the following header is enough to make this happen: `Accept: application/json`

In the specific case of the Pleiades service, it will return the same information as seen https://pleiades.stoa.org/places/570485/json (but without the need to modify the URL)

**Comment by GroovinChip** [comment]
I am able to retrieve the JSON data for the maps.
