### ISSUE TITLE
Identify a 3rd party map service which can be wrapped in a React component that mirador can use.

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#94]
Identify a 3rd party map service that we can use (OpenStreetMap, MapBox), which provides a JS library which produces maps, which can be wrapped in a React component that mirador can use. 
Need API Key: should never be save to GH.

**Comment by jabrah** [comment]
Could check out:

* https://react-leaflet.js.org/ (never used this one, but it looks interesting)
* https://www.mapbox.com/ (has a free tier with limits, this was fairly easy to use when I tried several years ago)

There are likely others that I don't know about

**Comment by GroovinChip** [comment]
Mapbox requires an account to use. I will look for others.

**Comment by GroovinChip** [comment]
I am currently using https://github.com/mariusandra/pigeon-maps. Doesn't require an API key, is very easy to use. Renders a basic map via OpenStreetMaps.
