### ISSUE TITLE
Create component to run along side the geo-reference data:to display the map

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#95]
distilled from information previously shared with Reuben by John.

**Comment by GroovinChip** [comment]
As mentioned in #94 I am using https://github.com/mariusandra/pigeon-maps. See results below:
![chrome_lXNTpC2SP6](https://user-images.githubusercontent.com/4250470/82357465-2bc98e00-99d3-11ea-8eb8-0a60fae15234.png)
I am able to render a basic map out of the latitude and longitude from the placeides map JSON. I'm not really happy with the black and white - the library is supposed to load OpenStreetMap map tiles by default, so I will raise an issue on the PidgeonMap repo to see what's going on and what can be done to fix it.

EDIT: Issue filed - https://github.com/mariusandra/pigeon-maps/issues/98
